services:
  - type: web
    name: haulagex-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: haulagex-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_TTL
        value: 15m
      - key: JWT_REFRESH_TTL
        value: 168h
      - key: NOSTRA_API_KEY
        value: "GjfpmCOVx(EULXMU3lEvydT3KyY84tL0oMGBuUdXeSw5Pi3)ySpHprldPJxlEZ5vn8J9JiZy6tLZTsUko6jEqfW=====2"
      - key: OCR_SERVICE_URL
        value: "https://am1anb-haulagex-ocr.hf.space"

databases:
  - name: haulagex-db
    databaseName: haulagex
    plan: free
